### ISSUE TITLE
binding affinity embedding dimesion issue

### ISSUE THREAD

**Issue by rokieplayer20** [guanjq/targetdiff#11]
I moved scripts/property_prediction/inference.py into targetdiff directory.
I used "python inference.py --ckpt_path pretrained_models/egnn_pdbbind_v2016.pt --protein_path examples/1h36_A_rec_1h36_r88_lig_tt_docked_0_pocket10.pdb --ligand_path examples/1h36_A_rec_1h36_r88_lig_tt_docked_0.sdf"

I encounted 
RuntimeError: Error(s) in loading state_dict for PropPredNet:
        size mismatch for ligand_atom_emb.weight: copying a param with shape torch.Size([256, 30]) from checkpoint, the shape in current model is torch.Size([256, 31]).

The embedding dimension is different from each other.

**Comment by guanjq** [comment]
Please refer to the issue. #1  It should be the problem of RDKit version.

**Comment by rokieplayer20** [comment]
> Please refer to the issue. #1 It should be the problem of RDKit version.
This is rdkit version.
rdkit=2023.03.2=py38h36d2b2f_0

I modified the versions of the package environment becasue there are packages that are compatible with the authors' environment versions as mentioned on github.



for the reference....
this is the rest versions


name: targetdiff
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py38h01eb140_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - blinker=1.6.2=pyhd8ed1ab_0
  - boltons=23.0.0=py38h06a4308_0
  - boost=1.78.0=py38h4e30db6_4
  - boost-cpp=1.78.0=h6582d0a_3
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py38hfa26641_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=h35add3b_1015
  - certifi=2023.5.7=py38h06a4308_0
  - cffi=1.15.1=py38h4a40e3a_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - conda=23.5.0=py38h06a4308_0
  - conda-package-handling=2.1.0=py38h06a4308_0
  - conda-package-streaming=0.8.0=py38h06a4308_0
  - contourpy=1.1.0=py38h7f3f72f_0
  - cryptography=41.0.1=py38hcdda232_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - easydict=1.9=py_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3=hf484d3e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.40.0=py38h01eb140_0
  - freetype=2.12.1=hca18f0e_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.3.3=py38h0a891b7_0
  - gettext=0.21.1=h27087fc_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=2.17.3=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - greenlet=2.0.2=py38h17151c0_1
  - grpcio=1.56.0=py38h94a1851_2
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py38h43d8883_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.3=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libgrpc=1.56.0=h3905398_2
  - libhwloc=2.9.1=nocuda_h7313eea_6
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.23.3=hd1fb520_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.3=py38h01eb140_0
  - matplotlib-base=3.7.1=py38hd6c3c57_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - multidict=6.0.4=py38h1de0b5d_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hcb278e6_0
  - nettle=3.6=he412f7d_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openbabel=3.1.1=py38hb38ef42_7
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py38h01efb38_0
  - pcre2=10.40=hc3806b6_0
  - pillow=9.4.0=py38hde6dc18_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=1.0.0=py38h06a4308_1
  - protobuf=4.23.3=py38h830738e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycairo=1.24.0=py38h1a1917b_0
  - pycosat=0.6.4=py38h5eee18b_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.17=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-lmdb=1.4.1=py38h8dc9893_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pytorch=1.13.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_5
  - rdkit=2023.03.2=py38h36d2b2f_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - reportlab=4.0.4=py38h01eb140_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py38h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py38h5eee18b_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.18=py38h01eb140_0
  - tbb=2021.9.0=hf52228f_0
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h3d167d9_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=0.13.1=py38_cu117
  - torchvision=0.14.1=py38_cu117
  - tqdm=4.65.0=py38hb070fc8_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - unicodedata2=15.0.0=py38h0a891b7_0
  - urllib3=2.0.3=pyhd8ed1ab_1
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py38h01eb140_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py38h5eee18b_0
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - autodocktools-py3==1.5.7.post1+7.g725082b
      - blessed==1.20.0
      - docutils==0.17.1
      - gpustat==1.1
      - jinja2==3.1.2
      - joblib==1.3.1
      - meeko==0.1.dev3
      - mmcif-pdbx==2.0.1
      - numpy==1.20.3
      - nvidia-ml-py==11.525.131
      - pdb2pqr==3.6.1
      - propka==3.5.0
      - psutil==5.9.5
      - pyg-lib==0.2.0+pt113cu117
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - threadpoolctl==3.1.0
      - torch-cluster==1.6.1+pt113cu117
      - torch-geometric==2.3.1
      - torch-scatter==2.1.1+pt113cu117
      - torch-sparse==0.6.17+pt113cu117
      - torch-spline-conv==1.2.2+pt113cu117
      - vina==1.2.2
      - wcwidth==0.2.6

**Comment by rokieplayer20** [comment]
It would be nice!
