### ISSUE TITLE
A Bug with the Estimation of Pocket Size

### ISSUE THREAD

**Issue by linhaowei1** [guanjq/targetdiff#13]
Hello Jiaqi,

Thanks for your fantastic work! I am using targetdiff and this repo for research purpose. When I read the code for ligand sampling with diffusion process, I suspected that there is a bug with the pocket size estimation:

```python3
n_data = batch_size if i < num_batch - 1 else num_samples - batch_size * (num_batch - 1)
batch = Batch.from_data_list([data.clone() for _ in range(n_data)], follow_batch=FOLLOW_BATCH).to(device)

with torch.no_grad():
    
    if sample_num_atoms == 'prior':
        pocket_size = atom_num.get_space_size(batch.protein_pos.detach().cpu().numpy())
        ligand_num_atoms = [atom_num.sample_atom_num(pocket_size).astype(int) for _ in range(n_data)]

```

The code is copied from `scripts/sample_diffusion.py` (some of the unimportant lines are omitted). As the paper introduced, it seems that you sampled 100 ligand candidates for 1 pocket, and `data` here corresponds to 1 pocket, which are copied for `n_data` times to form a batch. When you estimate the pocket size, the `atom_num.get_space_size` actually computes the pairwise distance of `batch.protein_pos` and returns the median of the top-10 pairwise distances. However, I think some of the protein atoms in `batch` are isolated and the pairwise distance between them do not make sense. I think the pocket_size estimation should be modified as:

```python3
pocket_size = atom_num.get_space_size(data.protein_pos.detach().cpu().numpy())
```

This bug also makes the execution of `scripts/sample_diffusion.py` or `scripts/sample_for_pocket.py` very slow, as the pairwise distance computation of ~10000 atoms within a batch is resource hungry. Besides, the estimation of pocket size is always larger than the corrected one.

I am not sure if I am correct. Looking forward to your reply!

**Comment by guanjq** [comment]
Hi,

Thank you for pointing this out! You are right! I need to use data.protein_pos (instead of batch.protein_pos) to compute the pocket size. However, it won't affect the running time much since the main computational cost comes from the sampling phase with the diffusion model.  I will fix this bug in the next commit, thanks!

**Comment by linhaowei1** [comment]
I saw your last commit that fixed this bug. Thanks for your prompt reply!
