### ISSUE TITLE
why the `model_type` setting in `training.yml` is `uni_o2`?

### ISSUE THREAD

**Issue by daisy-zzy** [guanjq/targetdiff#22]
Thank you for your great work and open-source code!
According to the guide, to train the model from scratch, we have to run:
`python scripts/train_diffusion.py configs/training.yml`
However, the `model_type` setting in `training.yml` is `uni_o2`, which means the denoising process will use `UniTransformerO2TwoUpdateGeneral` instead of `EGNN` as the refine net. Is this a mistake or is it the common case in training? @guanjq

**Comment by PzySeere** [comment]
hi, i also want the answer to this question. could u pls share the results? :) @zooay-zzy

**Comment by ShuRenyi211** [comment]
这个应该是作者后面重新换了架构吧，不管是EGNN还是其他的一些模型架构都是希望努力挖掘口袋和配体的融合信息。我不知道这样理解是否正确。我是刚刚接触这个领域，如果有错误，请批评指正
