### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/crossdocked_v1.1_rmsd1.0_pocket10/index.pkl'

### ISSUE THREAD

**Issue by yyou1996** [guanjq/targetdiff#3]
Dear authors,

Thanks for your great work. It seems the training code `python scripts/train_diffusion.py configs/training.yml` would cast a file missing error as described in the title, and I cannot find `/data/crossdocked_v1.1_rmsd1.0_pocket10/index.pkl` in the provided [google drive](https://drive.google.com/drive/folders/1j21cc7-97TedKh_El5E34yI8o5ckI7eK?usp=share_link).

**Comment by BJWiley233** [comment]
Please reopen since this directory `/data/crossdocked_v1.1_rmsd1.0_pocket10` does not exist
