### ISSUE TITLE
如何对在对指定的一个口袋进行采样后将结果转换为sdf文件？

### ISSUE THREAD

**Issue by InvincibleZZH** [guanjq/targetdiff#8]
我在手动制作了一个小分子结合口袋之后使用sample_for_poocket.py得到了sample.pt文件，但接下来应该如何使用其他代码倒出算法能够生成的小分子的sdf？

**Comment by guanjq** [comment]
Hi, sorry for the late response. I have updated the sample_for_pocket.py. It will reconstruct the sampled molecules and save them to {$result_path}/sdf now. If you have installed py3Dmol, you can simply check the sampled mol with the following code:
```python
from utils.visualize import visualize_complex

with open('examples/1h36_A_rec_1h36_r88_lig_tt_docked_0_pocket10.pdb', 'r') as f:
    pdb_block = f.read()
with open('outputs_pdb/sdf/000.sdf', 'r') as f:
    sdf_block = f.read()
        
visualize_complex(pdb_block, sdf_block, show_ligand_surface=False)
```
